apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml7ma-frontend
  labels:
    app: ml7ma-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml7ma-frontend
  template:
    metadata:
      labels:
        app: ml7ma-frontend
    spec:
      containers:
        - name: ml7ma-frontend
          image: eladwy/frontend:e9db97eb6ff08cf041e1e9c34e9591cd37a0acd0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: ml7ma-config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: ml7ma-config
          configMap:
            name: ml7ma-config
