apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml7ma-backend
  labels:
    app: ml7ma-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml7ma-backend
  template:
    metadata:
      labels:
        app: ml7ma-backend
    spec:
      initContainers:
        - name: run-migrations
          image: eladwy/backend:5d72ec3848ae885938a6b3f3c7a6271099abd0a0
          command: ["sh", "-c"]
          args:
            - |
              python manage.py migrate --no-input && \
              python manage.py createcachetable
          envFrom:
            - secretRef:
                name: mysql-secret
      containers:
        - name: ml7ma-backend
          image: eladwy/backend:5d72ec3848ae885938a6b3f3c7a6271099abd0a0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mysql-secret
                
